#!/bin/bash
set -e

DB_USER=trainer
DB_NAME=workoutlog
DB_PASS=password

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}';
  CREATE DATABASE ${DB_NAME};
  GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL
